### ISSUE TITLE
configure issues with recent libsbml and sundials versions

### ISSUE THREAD

**Issue by smoretti** [raim/SBML_odeSolver#5]
Hi

I try to install SBML_odeSolver but have issues at the configure step with recent versions of libsbml (5.17.0) and sundials (3.2.0).

About sundials, I managed to pass the configure step by tweaking the configure script a bit. Then the make command fails with this error message:
```
In file included from ./sbmlsolver/cvodeData.h:51:0,
                 from sbmlsolver/arithmeticCompiler.h:51,
                 from arithmeticCompiler.c:43:
./sbmlsolver/odeModel.h:49:33: fatal error: cvodes/cvodes_dense.h: No such file or directory
 #include <cvodes/cvodes_dense.h>
```
It looks cvodes/cvodes_dense.h is no longer available in sundials 3.2.0.

About libsbml, headers and libraries are found but the code run to test libsbml is maybe out-dated and does not work with libsbml 5.17.0
```
checking for SBML Library headers... yes
checking for SBML Library... yes
checking for correct functioning of SBML... no:
                   CPPFLAGS=-I/usr/include 
                   LDFLAGS=-Wl,-rpath,/usr/lib64 -L/usr/lib64 
                   LIBS=-lsbml -lxml2 -ldl
```

Also I have a general problem with most of my libraries being in /usr/lib64, not in /usr/lib.
The configure step try to guess the library path sometimes wrongly.

Thanks

**Comment by raim** [comment]
Thanks for reporting.
The current SOSlib works only with Sundials 2.4.0 and libSBML 3.4.1. You could install those locally and use --with-sundials and --with-libsbml flags for configure.
The lib64 is actually searched in the configure scripts, and should be found, if libs with extensions .so, .sl or .dylib are present (see file config/sbml.m4. Perhaps try the --with flags?

**Comment by smoretti** [comment]
Thanks for your feedback.
Do you plan to update SOSlib to sundials 3 and libSBML 5?
